---
:ems:
  :ems_dummy_provider:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :power:
          :critical:
            - DUMMY_PROVIDER_instance_power_on
            - DUMMY_PROVIDER_instance_power_off
:ems_refresh:
  :dummy_provider:
    # Switches refresh to graph refresh on [Graph refresh only]
    :allow_targeted_refresh: true
    :inventory_collections:
      # Strategy for saving, another allowed is batch, doing batch SQL queries [Graph refresh only]
      :saver_strategy: batch
:http_proxy:
  :dummy_provider:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_dummy: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_dummy_provider:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_dummy_provider: {}
      :ems_refresh_worker:
        :ems_refresh_worker_dummy_provider: {}
